services:
  - type: web
    name: rabbitmq
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    ports:
      - 15672:15672  # Management UI
      - 5672:5672    # AMQP port
