services:
  - type: web
    name: rabbitmq-ui
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    ports:
      - port: 15672
        name: http
        protocol: tcp

  - type: private_service
    name: rabbitmq-amqp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    ports:
      - port: 5672
        protocol: tcp
